<?php

return [
    'form_class' => \Hynek\Form\Form::class,
    'default_form_container' => \Hynek\Form\FormContainer::class,
    'default_control_container' => \Hynek\Form\ControlContainer::class,
    'default_form_builder' => \Hynek\Form\FormBuilder::class,
    'default_label' => \Hynek\Form\Label::class,
    'default_help_text' => \Hynek\Form\HelpText::class,
    'default_error' => \Hynek\Form\Error::class,
    'elements_collection' => \Hynek\Form\ElementsCollection::class,
    'controls' => [
        'input' => \Hynek\Form\Controls\Input::class,
        'textarea' => \Hynek\Form\Controls\TextArea::class,
        'select' => \Hynek\Form\Controls\Select::class,
        'checkbox' => \Hynek\Form\Controls\Checkbox::class,
        'checkbox-group' => \Hynek\Form\Controls\CheckboxGroup::class,
        'radio' => \Hynek\Form\Controls\Radio::class,
        'radio-group' => \Hynek\Form\Controls\RadioGroup::class,
        'button' => \Hynek\Form\Controls\Button::class,
    ],
    'views' => [
        'form' => 'form::form',
        'form_container' => 'form::form-container',
        'control_container' => 'form::control-container',
        'input' => 'form::controls.input',
        'textarea' => 'form::controls.textarea',
        'select' => 'form::controls.select',
        'checkbox' => 'form::controls.checkbox',
        'checkbox-group' => 'form::controls.checkbox.group',
        'radio' => 'form::controls.radio',
        'button' => 'form::controls.button',
        'label' => 'form::label',
        'help_text' => 'form::help-text',
        'error' => 'form::error',
    ],
];
